<?php
/**
 * Created by PhpStorm.
 * User: glpz
 * Date: 18/08/18
 * Time: 22:12
 */

namespace daxslab\cmsclient\widgets;

use Yii;
use yii\base\Widget;
use yii\base\ErrorException;

abstract class CMSWidget extends Widget
{

    public $id = null;

    public $page = null;

    public $render_title = true;

    public $render_abstract = true;

    public function init()
    {
        if ($this->page == null) {
            throw new ErrorException('page must be set for TextBlock');
        }

        if ($this->id == null) {
            $this->id = $this->getId();
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    protected function getPage($slug)
    {
        $page = Yii::$app->cmsClient->getContent($this->page);
        if (!$page) {
            throw new ErrorException(Yii::t('app', 'Content "{page}" not found', [
                'page' => $this->page,
            ]));
        }
        return $page;
    }

    protected function getSubpages($limit = 3)
    {
        $pages = Yii::$app->cmsClient->getContentChildren($this->page, $limit);
        return $pages;
    }

}